service: aws-node-http-api-project

custom:
  defaultStage: DESA
  parametros:
    DESA: local
    TEST: VALOR
    PROD: VALOR
  parametro: ${self:custom.parametros.${self:provider.stage}}
  stages:
    DESA: desa
    TEST: test
    PROD: prod
  entorno:
    DESA: DESARROLLO
    TEST: TEST
    PROD: PRODUCCION
  regions:
    code:
      DESA: us-east-2
      TEST: us-east-2
      PROD: us-east-1
    abrev:
      DESA: UE2
      TEST: UE2
      PROD: UE1
  account:
    DESA: 332713981074
    TEST: 332713981074
    PROD: 332713981074
  awsLambdaRoleName:
    local: TSC-AWS-PRUEBA 
    VALOR: TSC-AWS-PRUEBA
  bucket:
    UE2: tsc-despliegues
    UE1: tsc-despliegues-prod
  regionAbrev: ${self:custom.regions.abrev.${self:provider.stage}}
provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 300
  versionFunctions: false
  tracing:
    lambda: true
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${self:custom.regions.code.${self:provider.stage}}
  stackName: ${self:custom.regionAbrev}TSC${self:provider.stage}REG001
  deploymentBucket:
    name: ${self:custom.bucket.${self:custom.regionAbrev}}
  deploymentPrefix: serverless
  role: arn:aws:iam::${self:custom.account.${self:provider.stage}}:role/${self:custom.awsLambdaRoleName.${self:custom.parametro}}
  endpointType: regional

functions:
  crearCliente:
    handler: src/registrarCliente/index.handler
    name: ${self:custom.regionAbrev}TSC${self:provider.stage}LMBREG001
    description:
    memorySize: 512
    tags:
      NAME: TSC-PRUEBAS-CONCEPTOS
